{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-1.2.4.jar",
          "url": "crafter-1.2.4.jar",
          "size": 983897,
          "sha512": "9ec2d4d03959742474df17e764c8d7bf67f3566f4c830e516beeb3ce64a87ce7d749b39e88a48b745622484a584ecdfce80651093d291a095b27b1c90120552f",
          "sha256": "cb932b0d54e20bec6e0391780baec1749ceaf2e8cd5299607a0d2f4b7c83988d",
          "sha1": "374ec267a67a538daeb6391aa4ce1b46037c8290",
          "md5": "364e63d5ef85bba6d49336c5fff389e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.3.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "org.quiltmc.loom.no_remap",
          "module": "org.quiltmc.loom.no_remap.gradle.plugin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.14.10"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "7.0.15"
          }
        },
        {
          "group": "net.minecraftforge.jarjar",
          "module": "net.minecraftforge.jarjar.gradle.plugin",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.140"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.22.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-regex-dsl",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "lapis-annotations",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "lapis",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-1.2.4.jar",
          "url": "crafter-1.2.4.jar",
          "size": 983897,
          "sha512": "9ec2d4d03959742474df17e764c8d7bf67f3566f4c830e516beeb3ce64a87ce7d749b39e88a48b745622484a584ecdfce80651093d291a095b27b1c90120552f",
          "sha256": "cb932b0d54e20bec6e0391780baec1749ceaf2e8cd5299607a0d2f4b7c83988d",
          "sha1": "374ec267a67a538daeb6391aa4ce1b46037c8290",
          "md5": "364e63d5ef85bba6d49336c5fff389e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.2.4-sources.jar",
          "url": "crafter-1.2.4-sources.jar",
          "size": 8610,
          "sha512": "add67bd5e457aa2f5c6ffd56d24f1276243cd3efece920452019ed9791df4de849ba1adbd67bc1fad7410fb0c7811ccc859c3884c21672ea850cc8c6f5663b01",
          "sha256": "33046f99bf0365251a1c2b1ccce836e1aa1a24234dfc362640a18e1d9c7ee0a3",
          "sha1": "1ced05db00e2fb8def3f85a014c5e2571b0673de",
          "md5": "82c80683a555a4045d320fd394a794e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.2.4-javadoc.jar",
          "url": "crafter-1.2.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
