{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-1.1.1.jar",
          "url": "crafter-1.1.1.jar",
          "size": 1086831,
          "sha512": "4e97a1517fbb3a42883a59afc6b200f548775b43e24c4141fd2f41b7b6d7d65e5ddb2574c6fffd7e510fe6d340365c97bdf9d054cbc403f5c51897e63b0225ff",
          "sha256": "1a7fe694b2c769f76f7ee290c6f6030fe0935daca601f1c6f0795ef63b5d39a4",
          "sha1": "e38b274a6e71d01a558d98bae9876cffdf5ac89a",
          "md5": "c219b2f466b21bc63d6ab5a9b7bf690d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.0.21-1.0.25"
          }
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-regex-dsl",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-1.1.1.jar",
          "url": "crafter-1.1.1.jar",
          "size": 1086831,
          "sha512": "4e97a1517fbb3a42883a59afc6b200f548775b43e24c4141fd2f41b7b6d7d65e5ddb2574c6fffd7e510fe6d340365c97bdf9d054cbc403f5c51897e63b0225ff",
          "sha256": "1a7fe694b2c769f76f7ee290c6f6030fe0935daca601f1c6f0795ef63b5d39a4",
          "sha1": "e38b274a6e71d01a558d98bae9876cffdf5ac89a",
          "md5": "c219b2f466b21bc63d6ab5a9b7bf690d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.1.1-sources.jar",
          "url": "crafter-1.1.1-sources.jar",
          "size": 8424,
          "sha512": "ed7d4b6d97fed9a37b14ebc25ee12dba3591168295db03de64b7d61ac192f3fd4e9593aebe9df0fe0b3597f669065103ac4f9b4b688b278935591068334cca76",
          "sha256": "e45e6ada9b8601c7b3d09232ea7dae8e9795350884a332a6ddac93c9de98ad84",
          "sha1": "ee5a5ff9990d3f8e21a2f3b748de48be0cf2a680",
          "md5": "59b7d6f9769810c9df0fcef8b94b7146"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.1.1-javadoc.jar",
          "url": "crafter-1.1.1-javadoc.jar",
          "size": 261,
          "sha512": "b1864df22899f7d8e8f241912ffe0a552e8c53f0a54aa7d123bc5e04873c0abf34a96b526321b80313fd514b606f0f506b75604734f6a018d427f8d0b5a0474f",
          "sha256": "8500e7d0003edf8c5b602f5fa14e1c72d99c6826c3fea8335593f4acad4f0bbc",
          "sha1": "05bbba32cdabdf561b80ae08f5f93f7df86159f0",
          "md5": "cc703f93dc93b87bb4e27055147ab01b"
        }
      ]
    }
  ]
}
