{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-0.2.1.jar",
          "url": "crafter-0.2.1.jar",
          "size": 720496,
          "sha512": "838026b12f7120c76dcef39d9b2646e7c2b7a2d4af511262fde61430d8c2988ac01579153856a9ed050f18f85f4f3a8cbdc9d66cb018233362bf31066f81bbca",
          "sha256": "d56d0eec1e77251cc177bb1f9ebe7283dd39fb745f6363ed26d8220aa45839ad",
          "sha1": "81b475cfaf5faa47a6e0bf1d39d0d4fd9f5ea075",
          "md5": "570fccf3b18b492a4e8640e36c1dbf34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.parchmentmc.librarian.forgegradle",
          "module": "org.parchmentmc.librarian.forgegradle.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.1"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-0.2.1.jar",
          "url": "crafter-0.2.1.jar",
          "size": 720496,
          "sha512": "838026b12f7120c76dcef39d9b2646e7c2b7a2d4af511262fde61430d8c2988ac01579153856a9ed050f18f85f4f3a8cbdc9d66cb018233362bf31066f81bbca",
          "sha256": "d56d0eec1e77251cc177bb1f9ebe7283dd39fb745f6363ed26d8220aa45839ad",
          "sha1": "81b475cfaf5faa47a6e0bf1d39d0d4fd9f5ea075",
          "md5": "570fccf3b18b492a4e8640e36c1dbf34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.2.1-sources.jar",
          "url": "crafter-0.2.1-sources.jar",
          "size": 12681,
          "sha512": "cc81502ee977b882575412728119a662c0e251d09a96813091bdf99a70ee87483edabc4a65a923c44cf824de12750643a47196d383290498ff2d2c02b7120c3d",
          "sha256": "b917ae142a1e483a109b003938e1ad8b7b58fffceaec6c6696ad526bbbac27f3",
          "sha1": "95a585221a0c266faa38c43620cbd6b8bb774c96",
          "md5": "fa3d46c1fe97f63559bdf1aefba4a62b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.2.1-javadoc.jar",
          "url": "crafter-0.2.1-javadoc.jar",
          "size": 261,
          "sha512": "4676c730e2fac3409bdffcc57fa0f7a5ecf17dcff4b8a26d34afa02fd03da70c1db7e324dde4a4d0afb376f47329957d46e7f0c205a21fd99891234c2d791091",
          "sha256": "86252342a47cc18ae1d224d890b536b5b20005568ddec5f201449aae5e5d5f8a",
          "sha1": "14630b6760ea1fcaba48b959314be41428a10a80",
          "md5": "d6f10bf7358f47c58070523b89c3af4e"
        }
      ]
    }
  ]
}
