[versions]
projektor = "5.+"

kotlin = "2.2.21"

ksp = "2.2.21-2.0.5"
kotlin-serialization-json = "1.7.3"
kotlin-serialization-xml = "0.90.1"
ktor = "3.4.0"

java-poet = "0.11.0"
jsoup = "1.21.2"

kotlin-utils = "0.10.1"
kotlin-regex-dsl = "0.10.1"
gradle-utils = "0.10.1"

bedrock = "1.0.6"

lapis = "0.8.4"

shadow-plugin = "9.4.0"
quilt-plugin = "1.15.1"
legacy-fabric-plugin = "1.15.3"
ornithe-plugin = "1.14.10"
babric-plugin = "1.15.3"
forge-plugin = "7.0.15"
forge-jarjar-plugin = "0.2.3"
neoforge-plugin = "2.0.140"

[plugins]
projektor = { id = "io.github.diskria.projektor", version.ref = "projektor" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlin-serialization-json" }
kotlin-serialization-xml = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "kotlin-serialization-xml" }
ktor = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }

java-poet = { group = "com.palantir.javapoet", name = "javapoet", version.ref = "java-poet" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

kotlin-utils = { group = "io.github.diskria", name = "kotlin-utils", version.ref = "kotlin-utils" }
kotlin-regex-dsl = { group = "io.github.diskria", name = "kotlin-regex-dsl", version.ref = "kotlin-regex-dsl" }
gradle-utils = { group = "io.github.diskria", name = "gradle-utils", version.ref = "gradle-utils" }

bedrock = { group = "io.github.recrafter", name = "bedrock", version.ref = "bedrock" }

lapis-annotations = { group = "io.github.recrafter", name = "lapis-annotations", version.ref = "lapis" }
lapis-ksp = { group = "io.github.recrafter", name = "lapis", version.ref = "lapis" }

kotlin-jvm-plugin = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
ksp-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

shadow-plugin = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow-plugin" }
quilt-plugin = { group = "org.quiltmc.loom", name = "org.quiltmc.loom.gradle.plugin", version.ref = "quilt-plugin" }
legacy-fabric-plugin = { group = "legacy-looming", name = "legacy-looming.gradle.plugin", version.ref = "legacy-fabric-plugin" }
ornithe-plugin = { group = "ploceus", name = "ploceus.gradle.plugin", version.ref = "ornithe-plugin" }
babric-plugin = { group = "babric-loom-extension", name = "babric-loom-extension.gradle.plugin", version.ref = "babric-plugin" }
forge-plugin = { group = "net.minecraftforge.gradle", name = "net.minecraftforge.gradle.gradle.plugin", version.ref = "forge-plugin" }
forge-jarjar-plugin = { group = "net.minecraftforge.jarjar", name = "net.minecraftforge.jarjar.gradle.plugin", version.ref = "forge-jarjar-plugin" }
neoforge-plugin = { group = "net.neoforged.moddev", name = "net.neoforged.moddev.gradle.plugin", version.ref = "neoforge-plugin" }

[bundles]
diskria-utils = [
    "kotlin-utils",
    "kotlin-regex-dsl",
    "gradle-utils",
]
kotlin-plugins = [
    "kotlin-jvm-plugin",
    "kotlin-serialization-plugin",
    "ksp-plugin",
]
gradle-plugins = [
    "shadow-plugin",
    "quilt-plugin",
    "legacy-fabric-plugin",
    "ornithe-plugin",
    "babric-plugin",
    "forge-plugin",
    "forge-jarjar-plugin",
    "neoforge-plugin",
]
lapis = [
    "lapis-annotations",
    "lapis-ksp",
]
