{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-0.3.1.jar",
          "url": "crafter-0.3.1.jar",
          "size": 923838,
          "sha512": "52f51b5cfc4ada36f529f2b6579f7b424e9e75c291dff7e3516a003f2254c9b2bf0bf936191234abc52c15195b2b29c0e7975dce941ed72275163eccb9e7d3dc",
          "sha256": "ad1ba7a823a7694ab8eb3852727e0d3efc68215c6ad49ce997aaef454a99cf8d",
          "sha1": "4c87dba0b9463f2cf93a14d755d6ab39446b7dff",
          "md5": "1da5f18c8d9d03f61f39ccf08100324d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-0.3.1.jar",
          "url": "crafter-0.3.1.jar",
          "size": 923838,
          "sha512": "52f51b5cfc4ada36f529f2b6579f7b424e9e75c291dff7e3516a003f2254c9b2bf0bf936191234abc52c15195b2b29c0e7975dce941ed72275163eccb9e7d3dc",
          "sha256": "ad1ba7a823a7694ab8eb3852727e0d3efc68215c6ad49ce997aaef454a99cf8d",
          "sha1": "4c87dba0b9463f2cf93a14d755d6ab39446b7dff",
          "md5": "1da5f18c8d9d03f61f39ccf08100324d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.3.1-sources.jar",
          "url": "crafter-0.3.1-sources.jar",
          "size": 7865,
          "sha512": "d4e3ef918e54d955476921424a9ff58934e395febfdb66ac7c46666e5874ef6e7bfc24e7fdea810d4e261c2aa8c0edb70684aa99815de17ff326ee67b335d5f6",
          "sha256": "8e7b300f56fb9f5fd49c41852b157d5559235f27b67837ab361399e78c68e593",
          "sha1": "a344c8e9bc82837155c088b6ec08852be23a6210",
          "md5": "8e1700619484892f9fe8be33b7e1fabb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.3.1-javadoc.jar",
          "url": "crafter-0.3.1-javadoc.jar",
          "size": 261,
          "sha512": "dda0a3e8530f06c8200b2b56d4ac0cc0e7d86f0c7f26d79df7201037545abb2059a621fc71a671dc91ba46498e739cd9bb5a320e9e3259786bf35aeb0412db1d",
          "sha256": "5f466cefbf555cf0f7b766f32204dd981827e15e469b6d69477a39f2f5159fce",
          "sha1": "6a4e6d2bdc792fe26210d72a29ce5bb12e93f07d",
          "md5": "3bd218678b93c8667e04f6a1e944c04e"
        }
      ]
    }
  ]
}
