{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-1.0.0.jar",
          "url": "crafter-1.0.0.jar",
          "size": 1061414,
          "sha512": "29bc835f955924673098726d15b90b3f13c0c54cc751f61874a537bf1b3bfae6f707344c3841b15604caeb9a2b1cca16283b0d7cb47db19d9abb9cf02e65c228",
          "sha256": "2747a8db3894bad676b2e382f0101544cc061f8e07827931aafcb8d6f30b8e15",
          "sha1": "14d92b33493081841cc2b96a64bee0db6d061f71",
          "md5": "1a2e74062eaf02acede64c54d6fa09ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-1.0.0.jar",
          "url": "crafter-1.0.0.jar",
          "size": 1061414,
          "sha512": "29bc835f955924673098726d15b90b3f13c0c54cc751f61874a537bf1b3bfae6f707344c3841b15604caeb9a2b1cca16283b0d7cb47db19d9abb9cf02e65c228",
          "sha256": "2747a8db3894bad676b2e382f0101544cc061f8e07827931aafcb8d6f30b8e15",
          "sha1": "14d92b33493081841cc2b96a64bee0db6d061f71",
          "md5": "1a2e74062eaf02acede64c54d6fa09ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.0.0-sources.jar",
          "url": "crafter-1.0.0-sources.jar",
          "size": 8013,
          "sha512": "68d364c5f7cfe69b6e960fbbae47d59eae717df960265dc9d0d19b02b1b20d0fc7795124c6b8614bc46702e2377e082564f57a922cfb9f04ce5f09b8603d123b",
          "sha256": "252fbad74b88bc47a849eb19c0fb82154829f2fa91d6d1570a9c3d9e24f7072b",
          "sha1": "68f95173eb0f933c784567ba599f490bf7d41aa0",
          "md5": "4db4d46bb2eb621b38eaff6f29cd17f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.0.0-javadoc.jar",
          "url": "crafter-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "8bb3413cfeeefc6d9912f76a90fe9c35ce1d31d8e075e4d5fb3b272dc90875ad673dfadff9267958264e157ab18b12093ec84f2638fd3062aecfaaf0f2600bf9",
          "sha256": "33d53d0d7e66a4b228645d7a5ebe2621f7a7b37c9bb0a5ca3bbcd49cd41ba040",
          "sha1": "d5bb9e0a113385c47c8a17d4172a89531c3d1ce4",
          "md5": "22219f287d0b4e00ac95e9bb936c47a5"
        }
      ]
    }
  ]
}
