{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-1.2.0.jar",
          "url": "crafter-1.2.0.jar",
          "size": 972077,
          "sha512": "f91350e5ba2bb06e0dbc21a81ab8df76c34f0a473511a5e4048acc7cc0f2f585e61b73c4b1ce224dd2f96fbf82ac6fcc84064a17468a3e591244bcce73787fc2",
          "sha256": "0953c051a70122edd2ffe5fed2a3a09a16597781b014ba926b0fee30b8136e65",
          "sha1": "223418b804fb1fac2f79d29369f55427207caf0e",
          "md5": "6b34cbf47c4ead44fb2c28dd39005d50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.2.21-2.0.5"
          }
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.14.10"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "7.0.15"
          }
        },
        {
          "group": "net.minecraftforge.jarjar",
          "module": "net.minecraftforge.jarjar.gradle.plugin",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.140"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-regex-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "lapis-annotations",
          "version": {
            "requires": "0.7.4"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "lapis",
          "version": {
            "requires": "0.7.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-1.2.0.jar",
          "url": "crafter-1.2.0.jar",
          "size": 972077,
          "sha512": "f91350e5ba2bb06e0dbc21a81ab8df76c34f0a473511a5e4048acc7cc0f2f585e61b73c4b1ce224dd2f96fbf82ac6fcc84064a17468a3e591244bcce73787fc2",
          "sha256": "0953c051a70122edd2ffe5fed2a3a09a16597781b014ba926b0fee30b8136e65",
          "sha1": "223418b804fb1fac2f79d29369f55427207caf0e",
          "md5": "6b34cbf47c4ead44fb2c28dd39005d50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.2.0-sources.jar",
          "url": "crafter-1.2.0-sources.jar",
          "size": 8208,
          "sha512": "d9415a3a4d7927858c7e5050d5d613db93dfa937e6a8e175f9bb7c4f57e94f01e7635c2a846de8d389437f8db4e90d8dc12b3d539a31aa857933ecca339accde",
          "sha256": "b6ca9c97ba46c70677032007bdef6f895812eacbc3347e21bceee9c94e049010",
          "sha1": "5406929b1c1ffbbf666c5840ea56e54fa074b01a",
          "md5": "3fca0381b988360e003b068a8f6a94d8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-1.2.0-javadoc.jar",
          "url": "crafter-1.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
