{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-0.2.4.jar",
          "url": "crafter-0.2.4.jar",
          "size": 846871,
          "sha512": "ec016d90638ed291cb4aa6619e660078d6a1d6b53facddb86f17e5355b9111abe132337fcdc0e7ff59e6f83ee3020d473975ca58f7bcef4022a70ce283780568",
          "sha256": "d0d0a9d28cee87b02c8c21065ccb62921c751d30b21446a8c66e9d2b601e3a8b",
          "sha1": "7e08abaefe1f26601fc513f7776531bd54ea3d17",
          "md5": "ee7dfa454343de3594784b2574899b14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-0.2.4.jar",
          "url": "crafter-0.2.4.jar",
          "size": 846871,
          "sha512": "ec016d90638ed291cb4aa6619e660078d6a1d6b53facddb86f17e5355b9111abe132337fcdc0e7ff59e6f83ee3020d473975ca58f7bcef4022a70ce283780568",
          "sha256": "d0d0a9d28cee87b02c8c21065ccb62921c751d30b21446a8c66e9d2b601e3a8b",
          "sha1": "7e08abaefe1f26601fc513f7776531bd54ea3d17",
          "md5": "ee7dfa454343de3594784b2574899b14"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.2.4-sources.jar",
          "url": "crafter-0.2.4-sources.jar",
          "size": 7489,
          "sha512": "99aca32a0cd7dc8c9304cc401a6a8a097a7c815a4e87811fac480530494641ca2d15d5f016e321cc8548c0700955fe0e0e2d69fc9c8796bf0cf6a4cc08b8fcd4",
          "sha256": "4d72a7195b2d78713c29eaaed5613b5017a78bafb72cc511d92e6f087fe08f73",
          "sha1": "5c5585ce9dc88f40a9c5e7d2e5c12e4b8def68e0",
          "md5": "818f8f14a35489278a7ad383465725a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.2.4-javadoc.jar",
          "url": "crafter-0.2.4-javadoc.jar",
          "size": 261,
          "sha512": "73b9d6cbadaaa5d5a38877d71dea2c7f8142c19cf6a326b10bf1c963d9e7547a46a34f76ae5b87228ef2459c6d00c2e63e94290d80b253efee2d0a8ac1bb1f16",
          "sha256": "da533ae87d94a4a671a94aa87458eccd45e28431d97580d97a17ab7555e24b30",
          "sha1": "2ea16fbc51a9963419f0ca8f77d4acd259e7a7c8",
          "md5": "c86813825b026836e44f0c1be09e7f37"
        }
      ]
    }
  ]
}
