{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "0.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-0.3.5.jar",
          "url": "crafter-0.3.5.jar",
          "size": 1052605,
          "sha512": "e6afd93bcd5a1a804d74776ff50296988cd6c82f8a6e7fec4dda42a72f11a500926b211f146f280f5471f9684bc6633eeb07a0ba0dd95a8ff3be9e67c4f5a671",
          "sha256": "49d9d6cbfdc897bdf488c873cc86918750258f9d54a798912991340150009849",
          "sha1": "65516657c58c0c453103832527598b0d9e8795d0",
          "md5": "fbf795e4ed345e3a22e74473212c4357"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.quiltmc.loom",
          "module": "org.quiltmc.loom.gradle.plugin",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "babric-loom-extension",
          "module": "babric-loom-extension.gradle.plugin",
          "version": {
            "requires": "1.13.2"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-0.3.5.jar",
          "url": "crafter-0.3.5.jar",
          "size": 1052605,
          "sha512": "e6afd93bcd5a1a804d74776ff50296988cd6c82f8a6e7fec4dda42a72f11a500926b211f146f280f5471f9684bc6633eeb07a0ba0dd95a8ff3be9e67c4f5a671",
          "sha256": "49d9d6cbfdc897bdf488c873cc86918750258f9d54a798912991340150009849",
          "sha1": "65516657c58c0c453103832527598b0d9e8795d0",
          "md5": "fbf795e4ed345e3a22e74473212c4357"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.3.5-sources.jar",
          "url": "crafter-0.3.5-sources.jar",
          "size": 8015,
          "sha512": "f12967e7a9a919a79424a10b23b9dc89fe5f34aeb00d5ed66e71f9ce91a5119483e328334eba3fa88503c1b53e6c38de8ad94b93744dd8165ec4541d745aa3fb",
          "sha256": "136bbc7717b23430909bfbd30f2478d801e1f2bbba56710b52636fdde643b0cc",
          "sha1": "eaff3d7e3bd7354aa68d49c402ca693eba577585",
          "md5": "39b4788a6ebb4f8b7d6ab060062c49dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.3.5-javadoc.jar",
          "url": "crafter-0.3.5-javadoc.jar",
          "size": 261,
          "sha512": "8f27a22cdcb9b7ac3c5c62948aba5a921f228e5dc8ae9636c5a5cb3da217ff65186e5ec679d3d75bad9e7daf5147095400372e9972101c07b2d09b46d30b9c1a",
          "sha256": "796bfe33e4e15ac5c26f09e7a198d789e4861ef8360fd39cda721001f6155c3a",
          "sha1": "fc48c3b2e616fd65af9cd41f2f223c3080d91560",
          "md5": "d6a0a1cd2d6dd0930163b8bee9fbd2c4"
        }
      ]
    }
  ]
}
