{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.recrafter",
    "module": "crafter",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "crafter-0.1.0.jar",
          "url": "crafter-0.1.0.jar",
          "size": 671104,
          "sha512": "797b380102a142c5674c8b0eaa98fb2e32eb232e98b7282bdc0a138e8e742968014417eec06785f1756e82e8b1173a042a99b2d12b94f8db74a124a8c337d1d0",
          "sha256": "4502e1bb36eb0cf0562ed753d57c538e0471223e8ceaacc407ae5b3d461fd205",
          "sha1": "a12249b3530772a512c047d626a75a83e22cc38b",
          "md5": "f4bfe2e010b0e599f223c067d80d77a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.parchmentmc.librarian.forgegradle",
          "module": "org.parchmentmc.librarian.forgegradle.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "io.github.recrafter",
          "module": "bedrock",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "crafter-0.1.0.jar",
          "url": "crafter-0.1.0.jar",
          "size": 671104,
          "sha512": "797b380102a142c5674c8b0eaa98fb2e32eb232e98b7282bdc0a138e8e742968014417eec06785f1756e82e8b1173a042a99b2d12b94f8db74a124a8c337d1d0",
          "sha256": "4502e1bb36eb0cf0562ed753d57c538e0471223e8ceaacc407ae5b3d461fd205",
          "sha1": "a12249b3530772a512c047d626a75a83e22cc38b",
          "md5": "f4bfe2e010b0e599f223c067d80d77a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.1.0-sources.jar",
          "url": "crafter-0.1.0-sources.jar",
          "size": 72862,
          "sha512": "38fe6356132bb04ac7c4042a840da08ebd54b7ca57665b550a57616f75c7a386d8541f88332da25090046f241754064c624a978b29bb7d0436fa41e3777cefe6",
          "sha256": "4b02eb37bb1036c1fe07a96ecc1678ed97f2a2afa47952671fcd2f53b76f7724",
          "sha1": "3c935100aa0b86aedbbf81ecb70a11f60a4a7222",
          "md5": "860c2a0902a4e4dd64fe0ac7ec0dcfd8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crafter-0.1.0-javadoc.jar",
          "url": "crafter-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "5fb803e1ab5e6fda651b59e297c21f2c2651f4a3a7af8852f06c1cc4d727450539450e76134b009d7fbf8b6ade5df4008b72175ea0adda6eb6528a06a7f5a72a",
          "sha256": "9f9782531e6df46d69bbd0480e2eaed206c6f59487998c2f90b34d6f0e2184df",
          "sha1": "f5a417a7194b3891dcf3f9f690e45e73de48fc40",
          "md5": "6335ec1aebc3dcd1ac9c124634919438"
        }
      ]
    }
  ]
}
